sudo: false

language: node_js

addons:
  chrome: stable

env:
  - MOZ_HEADLESS=1

before_install:
  google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &

script: npm run lint && npm run test-server-open && npm run test-node && npm run test-browser
after_script: npm run test-server-close

node_js:
  - "10"
  - "12"
  - "13"
  - "node"

cache:
  directories:
    - node_modules
    - $HOME/.npm

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    node: "node"
